#mssql data volume claim: mssql-mdf-volume.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-mdf-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  storageClassName: standard
  hostPath:
    path: /data/mssql/mdf/
