kind: PersistentVolume
apiVersion: v1
metadata:
  name: mssql-base-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  storageClassName: standard
  hostPath:
      path: /data/mssql/
