kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv0001
  labels:
    app: mongo
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
      path: /data/pv0001/
