apiVersion: v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
       - name: backend
         image: image=localhost:5000/backend
         ports:
         - containerPort: 8080
         env:
         - name: "SERVERPORT"
           value: "8080"
	 - name: "DBIP"
	   value: "192.168.99.100"
	 - name: "DBPORT"
	   value: "32291"
	 - name: "DBUSER"
	   value: "SA"
	 - name: "DBPASS"
	   value: "<YourStrong!Passw0rd>"

