apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: status
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: status
    spec:
      containers:
       - name: status
         image: localhost:5000/status
         ports:
         - containerPort: 3000
         env:
          - name: "SERVERPORT"
            value: "3000"

